# Generated by Django 2.1.2 on 2019-04-13 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cuenta',
            fields=[
                ('id_cuenta', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=1000)),
                ('rut', models.CharField(max_length=15)),
                ('correoAsociado', models.TextField()),
                ('tipo_usuario', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('cuenta_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='App.Cuenta')),
                ('fec_nac', models.DateField(max_length=15)),
                ('esactiva', models.BooleanField(default=True)),
            ],
            bases=('App.cuenta',),
        ),
    ]
