# Generated by Django 2.1.2 on 2019-05-11 18:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fec_nac', models.DateField(max_length=15)),
                ('fec_ingreso', models.DateField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Cuenta',
            fields=[
                ('rut', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=1000, null=True)),
                ('correoAsociado', models.TextField(null=True)),
                ('fecha_registro', models.DateField(max_length=15, null=True)),
                ('comuna', models.CharField(max_length=1000, null=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fec_activacion', models.DateField(max_length=15, null=True)),
                ('direccion', models.CharField(max_length=150)),
                ('Cuenta', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='App.Cuenta')),
            ],
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id_evento', models.AutoField(max_length=15, primary_key=True, serialize=False)),
                ('fecha', models.DateField(max_length=15)),
                ('hora', models.DateTimeField(max_length=15)),
                ('comuna', models.CharField(max_length=15)),
                ('direccion', models.CharField(max_length=150)),
                ('cant_cupos', models.CharField(max_length=15)),
                ('pagReserva', models.BooleanField(default=True)),
                ('Empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.Empresa')),
            ],
        ),
        migrations.CreateModel(
            name='RegistroEmail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iduuid', models.CharField(max_length=1000, null=True)),
                ('Cuenta', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='App.Cuenta')),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id_reserva', models.AutoField(max_length=15, primary_key=True, serialize=False)),
                ('fecha', models.DateField(max_length=15)),
                ('hora', models.DateTimeField(max_length=15)),
                ('Evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.Evento')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fec_nac', models.DateField(max_length=15, null=True)),
                ('Cuenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.Cuenta')),
            ],
        ),
        migrations.CreateModel(
            name='Visita',
            fields=[
                ('id_visita', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_visita', models.DateField(max_length=15)),
                ('resolucion', models.CharField(max_length=5000, null=True)),
                ('Administrador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.Administrador')),
                ('Empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.Empresa')),
            ],
        ),
        migrations.AddField(
            model_name='reserva',
            name='Usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.Usuario'),
        ),
        migrations.AddField(
            model_name='administrador',
            name='Cuenta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='App.Cuenta'),
        ),
    ]
