# Generated by Django 2.1.2 on 2019-06-01 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='hora',
            field=models.TimeField(max_length=15),
        ),
    ]
