# Generated by Django 2.1.2 on 2019-04-19 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_auto_20190414_2134'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='administrador',
            name='cuenta_ptr',
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='cuenta_ptr',
        ),
        migrations.RemoveField(
            model_name='evento',
            name='Empresa',
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='Evento',
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='Usuario',
        ),
        migrations.DeleteModel(
            name='TipoUsuario',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='cuenta_ptr',
        ),
        migrations.RemoveField(
            model_name='visita',
            name='Administrador',
        ),
        migrations.RemoveField(
            model_name='visita',
            name='Empresa',
        ),
        migrations.RemoveField(
            model_name='cuenta',
            name='correoAsociado',
        ),
        migrations.RemoveField(
            model_name='cuenta',
            name='esactiva',
        ),
        migrations.RemoveField(
            model_name='cuenta',
            name='fecha_registro',
        ),
        migrations.RemoveField(
            model_name='cuenta',
            name='tipo_usuario',
        ),
        migrations.AlterField(
            model_name='cuenta',
            name='nombre',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='cuenta',
            name='rut',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.DeleteModel(
            name='Administrador',
        ),
        migrations.DeleteModel(
            name='Empresa',
        ),
        migrations.DeleteModel(
            name='Evento',
        ),
        migrations.DeleteModel(
            name='Reserva',
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
        migrations.DeleteModel(
            name='Visita',
        ),
    ]
