# Generated by Django 2.1.2 on 2019-04-20 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_auto_20190420_1005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuenta',
            name='id_cuenta',
            field=models.AutoField(max_length=15, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='cuenta',
            name='tipo_usuario',
            field=models.CharField(choices=[('Usuario', 'Usuario'), ('Empresa', 'Empresa'), ('Administrador', 'Administrador')], max_length=5, null=True),
        ),
    ]
