# Generated by Django 2.1.2 on 2019-04-21 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0011_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuenta',
            name='comuna',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='fec_nac',
            field=models.DateField(max_length=15, null=True),
        ),
    ]
