# Generated by Django 2.1.2 on 2019-05-01 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0015_registroemail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registroemail',
            name='user',
        ),
        migrations.AddField(
            model_name='registroemail',
            name='cuenta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='App.Cuenta'),
        ),
        migrations.AlterField(
            model_name='registroemail',
            name='iduuid',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
