# Generated by Django 2.1.2 on 2019-05-01 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0016_auto_20190501_1107'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registroemail',
            old_name='cuenta',
            new_name='Cuenta',
        ),
    ]
