# Generated by Django 2.1.2 on 2019-04-15 01:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('cuenta_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='App.Cuenta')),
                ('fec_nac', models.DateField(max_length=15)),
                ('fec_ingreso', models.DateField(max_length=15)),
            ],
            bases=('App.cuenta',),
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('cuenta_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='App.Cuenta')),
                ('fec_activacion', models.DateField(max_length=15)),
            ],
            bases=('App.cuenta',),
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id_evento', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('fecha', models.DateField(max_length=15)),
                ('hora', models.DateTimeField(max_length=15)),
                ('comuna', models.CharField(max_length=15)),
                ('direccion', models.CharField(max_length=15)),
                ('cant_cupos', models.CharField(max_length=15)),
                ('pagReserva', models.BooleanField(default=True)),
                ('Empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.Empresa')),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id_reserva', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('fecha', models.DateField(max_length=15)),
                ('hora', models.DateTimeField(max_length=15)),
                ('Evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.Evento')),
            ],
        ),
        migrations.CreateModel(
            name='TipoUsuario',
            fields=[
                ('id_tipo', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Visita',
            fields=[
                ('id_visita', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('fecha_visita', models.DateField(max_length=15)),
                ('resolucion', models.CharField(max_length=5000)),
                ('Administrador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.Administrador')),
                ('Empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.Empresa')),
            ],
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='esactiva',
        ),
        migrations.AddField(
            model_name='cuenta',
            name='esactiva',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='cuenta',
            name='fecha_registro',
            field=models.DateField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='reserva',
            name='Usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.Usuario'),
        ),
    ]
