# Generated by Django 2.1.2 on 2019-04-20 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0008_auto_20190420_1331'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cuenta',
            name='tipo_usuario',
        ),
    ]
