# Generated by Django 2.1.2 on 2019-04-20 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0006_auto_20190420_1227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuenta',
            name='rut',
            field=models.CharField(max_length=15, null=True, unique=True),
        ),
    ]
