# Generated by Django 2.1.2 on 2019-04-20 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0009_remove_cuenta_tipo_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='Cuenta',
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
