# Generated by Django 2.1.2 on 2019-04-20 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0010_auto_20190420_1417'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fec_nac', models.DateField(max_length=15)),
                ('Cuenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.Cuenta')),
            ],
        ),
    ]
