# Generated by Django 2.1.2 on 2019-04-21 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0012_auto_20190421_1544'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cuenta',
            name='esactiva',
        ),
    ]
